# Generated by Django 5.1.5 on 2025-03-03 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='infoextra',
            name='sobre_ti',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
