# Generated by Django 5.1.5 on 2025-03-03 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_infoextra_sobre_ti'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infoextra',
            name='sobre_ti',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
