# Generated by Django 5.1.5 on 2025-02-14 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jugador',
            name='categoria',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8')], default='8'),
        ),
        migrations.AddField(
            model_name='jugador',
            name='documento',
            field=models.CharField(default='99999999', max_length=8),
        ),
    ]
