# Generated by Django 5.1.5 on 2025-02-14 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0002_jugador_categoria_jugador_documento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jugador',
            name='participaciones',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='puntos',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
