# Generated by Django 5.1.5 on 2025-02-26 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0006_jugador_fecha_creacion_jugador_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jugador',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='fotosplayers'),
        ),
    ]
