# Generated by Django 5.1.5 on 2025-03-02 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0007_alter_jugador_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jugador',
            name='fecha_creacion',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
