# Generated by Django 5.1.5 on 2025-03-03 21:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0008_alter_jugador_fecha_creacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jugador',
            name='fecha_creacion',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
